# Generated by Django 6.0.1 on 2026-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_post_comments_count_post_image_post_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='instagram_user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
