# Generated by Django 6.0.1 on 2026-07-31 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('instagram', '0003_comment_instagram_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_message_id', models.CharField(blank=True, max_length=255)),
                ('sender_id', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('is_from_instagram', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.lead')),
            ],
        ),
    ]
